#!/bin/bash

mkdir -p src/dependencies
vcs import --input required.repos src/dependencies

set -o pipefail
while true; do
    exec 5>&2
    msg=$(colcon build --symlink-install 3>&2 2>&1 1>&3 | tee /dev/fd/5)
    exit_code=$?
    if [ $exit_code -eq "0" ] || ! [[ $msg =~  "Killed signal terminated program cc1plus" ]]; then
        (exit "$exit_code")
        break
    fi
done
